/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext.validation;

import org.eclipse.xtext.validation.Check;

import de.fhdo.ewks.ml_example.Context;
import de.fhdo.ewks.ml_example.Ml_examplePackage;
import de.fhdo.ewks.ml_example.Structure;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class StructureDslValidator extends AbstractStructureDslValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					StructureDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	@Check
	public void checkUniqueStructures(Context context) {
		int duplicateIndex = context.checkUniqueStructures();
		if (duplicateIndex > -1) {
			Structure duplicateStructure = context.getStructures().get(duplicateIndex);
			error("Duplicate structure " + duplicateStructure.getName(),
					duplicateStructure, Ml_examplePackage.Literals.STRUCTURE__NAME);
		}
	}
}
