/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StructureDslUiModule extends AbstractStructureDslUiModule {

	public StructureDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
