/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStructureDslScopeProvider extends DelegatingScopeProvider {
}
