/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StructureDslRuntimeModule extends AbstractStructureDslRuntimeModule {
}
