/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StructureDslStandaloneSetup extends StructureDslStandaloneSetupGenerated {

	public static void doSetup() {
		new StructureDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
