/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fhdo.ewks.ml_example.xtext.StructureDslRuntimeModule;
import de.fhdo.ewks.ml_example.xtext.StructureDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StructureDslIdeSetup extends StructureDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StructureDslRuntimeModule(), new StructureDslIdeModule()));
	}
	
}
