/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StructureDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/fhdo/ewks/ml_example/xtext/parser/antlr/internal/InternalStructureDsl.tokens");
	}
}
