/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.ewks.ml_example.xtext.parser.antlr;

import com.google.inject.Inject;
import de.fhdo.ewks.ml_example.xtext.parser.antlr.internal.InternalStructureDslParser;
import de.fhdo.ewks.ml_example.xtext.services.StructureDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class StructureDslParser extends AbstractAntlrParser {

	@Inject
	private StructureDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStructureDslParser createParser(XtextTokenStream stream) {
		return new InternalStructureDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Context";
	}

	public StructureDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StructureDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
